// Italian Municipalities to Province mapping & Province utilities

export const COMUNI_PROVINCE_MAP: Record<string, string> = {
  // MASSA-CARRARA (MS)
  "massa": "MS",
  "carrara": "MS",
  "montignoso": "MS",
  "aulla": "MS",
  "fivizzano": "MS",
  "pontremoli": "MS",
  "bagnone": "MS",
  "filattiera": "MS",
  "mulazzo": "MS",
  "podenzana": "MS",
  "licciana nardi": "MS",
  "tresana": "MS",
  "comano": "MS",
  "zeri": "MS",
  "villafranca in lunigiana": "MS",
  "casola in lunigiana": "MS",
  "fosdinovo": "MS",

  // LUCCA (LU)
  "lucca": "LU",
  "viareggio": "LU",
  "pietrasanta": "LU",
  "camaiore": "LU",
  "forte dei marmi": "LU",
  "seravezza": "LU",
  "stazzema": "LU",
  "massarosa": "LU",
  "capannori": "LU",
  "altopascio": "LU",
  "montecarlo": "LU",
  "barga": "LU",
  "castelnuovo di garfagnana": "LU",
  "coreglia antelminelli": "LU",
  "gallicano": "LU",
  "borgo a mozzano": "LU",
  "bagni di lucca": "LU",
  "porcari": "LU",
  "pescaglia": "LU",
  "minucciano": "LU",
  "camporgiano": "LU",
  "piazza al serchio": "LU",
  "villa collemandina": "LU",
  "san romano in garfagnana": "LU",
  "careggine": "LU",
  "fosciandora": "LU",
  "molazzana": "LU",
  "sillano giuncugnano": "LU",

  // LA SPEZIA (SP)
  "la spezia": "SP",
  "spezia": "SP",
  "sarzana": "SP",
  "lerici": "SP",
  "arcola": "SP",
  "castelnuovo magra": "SP",
  "santo stefano di magra": "SP",
  "portovenere": "SP",
  "porto venere": "SP",
  "ameglia": "SP",
  "ortonovo": "SP",
  "luni": "SP",
  "bolano": "SP",
  "vezzano ligure": "SP",
  "ricco del golfo di la spezia": "SP",
  "follo": "SP",
  "beverino": "SP",
  "calice al cornoviglio": "SP",
  "brugnato": "SP",
  "borghetto di vara": "SP",
  "pignone": "SP",
  "levanto": "SP",
  "bonassola": "SP",
  "framura": "SP",
  "deiva marina": "SP",
  "monterosso al mare": "SP",
  "vernazza": "SP",
  "corniglia": "SP",
  "riomaggiore": "SP",
  "zignago": "SP",
  "varese ligure": "SP",
  "maissana": "SP",
  "carro": "SP",
  "carrodano": "SP",

  // PISA (PI)
  "pisa": "PI",
  "cascina": "PI",
  "san giuliano terme": "PI",
  "pontedera": "PI",
  "san miniato": "PI",
  "volterra": "PI",
  "santa croce sull'arno": "PI",
  "castelfranco di sotto": "PI",
  "vecchiano": "PI",
  "calcinaia": "PI",
  "santa maria a monte": "PI",
  "casciana terme lari": "PI",
  "terricciola": "PI",
  "capannoli": "PI",
  "palaia": "PI",
  "peccioli": "PI",
  "montopoli in val d'arno": "PI",
  "fauglia": "PI",
  "crespina lorenzana": "PI",
  "orciano pisano": "PI",
  "riparbella": "PI",
  "montescudaio": "PI",
  "guardistallo": "PI",
  "casale marittimo": "PI",
  "castellina marittima": "PI",
  "chianni": "PI",
  "lajatico": "PI",
  "pomarance": "PI",
  "castelnuovo val di cecina": "PI",
  "montecatini val di cecina": "PI",

  // LIVORNO (LI)
  "livorno": "LI",
  "cecina": "LI",
  "rosignano marittimo": "LI",
  "piombino": "LI",
  "campiglia marittima": "LI",
  "suvereto": "LI",
  "castagneto carducci": "LI",
  "bibbona": "LI",
  "portoferraio": "LI",
  "campo nell'elba": "LI",
  "capoliveri": "LI",
  "porto azzurro": "LI",
  "rio": "LI",
  "marciana": "LI",
  "marciana marina": "LI",
  "capraia isola": "LI",

  // FIRENZE (FI)
  "firenze": "FI",
  "empoli": "FI",
  "scandicci": "FI",
  "sesto fiorentino": "FI",
  "campi bisenzio": "FI",
  "bagno a ripoli": "FI",
  "fiesole": "FI",
  "pontassieve": "FI",
  "borgo san lorenzo": "FI",
  "calenzano": "FI",
  "castelfiorentino": "FI",
  "certaldo": "FI",
  "figline e incisa valdarno": "FI",
  "fucecchio": "FI",
  "impruneta": "FI",
  "lastra a signa": "FI",
  "montelupo fiorentino": "FI",
  "montespertoli": "FI",
  "rignano sull'arno": "FI",
  "san casciano in val di pesa": "FI",
  "signa": "FI",
  "barberino tavarnelle": "FI",
  "vicchio": "FI",
  "barberino di mugello": "FI",
  "dicomano": "FI",
  "firenzuola": "FI",
  "marradi": "FI",
  "palazzuolo sul senio": "FI",
  "pelago": "FI",
  "reggello": "FI",
  "rufina": "FI",
  "scarperia e san piero": "FI",
  "vaglia": "FI",

  // PISTOIA (PT)
  "pistoia": "PT",
  "montecatini terme": "PT",
  "pescia": "PT",
  "quarrata": "PT",
  "agliana": "PT",
  "monsummano terme": "PT",
  "serravalle pistoiese": "PT",
  "buggiano": "PT",
  "chiesina uzzanese": "PT",
  "lamporecchio": "PT",
  "larciano": "PT",
  "massa e cozzile": "PT",
  "uzzano": "PT",
  "ponte buggianese": "PT",
  "abetone cutigliano": "PT",
  "san marcello piteglio": "PT",

  // PRATO (PO)
  "prato": "PO",
  "montemurlo": "PO",
  "carmignano": "PO",
  "poggio a caiano": "PO",
  "vaiano": "PO",
  "vernio": "PO",
  "cantagallo": "PO",

  // AREZZO (AR)
  "arezzo": "AR",
  "cortona": "AR",
  "montevarchi": "AR",
  "san giovanni valdarno": "AR",
  "terranuova bracciolini": "AR",
  "castiglion fiorentino": "AR",
  "sansepolcro": "AR",
  "bibbiena": "AR",
  "bucine": "AR",
  "cavriglia": "AR",
  "foiano della chiana": "AR",
  "lucignano": "AR",

  // SIENA (SI)
  "siena": "SI",
  "poggibonsi": "SI",
  "colle di val d'elsa": "SI",
  "montepulciano": "SI",
  "sinalunga": "SI",
  "sovicille": "SI",
  "monteriggioni": "SI",
  "castelnuovo berardenga": "SI",
  "chiusi": "SI",
  "san gimignano": "SI",

  // GROSSETO (GR)
  "grosseto": "GR",
  "follonica": "GR",
  "orbetello": "GR",
  "castiglione della pescaia": "GR",
  "monte argentario": "GR",
  "roccastrada": "GR",
  "massa marittima": "GR",
  "gavorrano": "GR",
  "manciano": "GR",
  "scansano": "GR",
  "pitigliano": "GR",

  // OTHER MAJOR CITIES & PROVINCES
  "roma": "RM",
  "milano": "MI",
  "torino": "TO",
  "napoli": "NA",
  "bologna": "BO",
  "genova": "GE",
  "bari": "BA",
  "palermo": "PA",
  "catania": "CT",
  "cagliari": "CA",
  "trento": "TN",
  "bolzano": "BZ",
  "trieste": "TS",
  "udine": "UD",
  "padova": "PD",
  "verona": "VR",
  "venezia": "VE",
  "brescia": "BS",
  "bergamo": "BG",
  "monza": "MB",
  "parma": "PR",
  "modena": "MO",
  "reggio emilia": "RE",
  "ferrara": "FE",
  "ravenna": "RA",
  "forli": "FC",
  "cesena": "FC",
  "rimini": "RN",
  "piacenza": "PC",
  "alessandria": "AL",
  "asti": "AT",
  "novara": "NO",
  "vercelli": "VC",
  "biella": "BI",
  "cuneo": "CN",
  "como": "CO",
  "lecco": "LC",
  "varese": "VA",
  "sondrio": "SO",
  "pavia": "PV",
  "cremona": "CR",
  "mantova": "MN",
  "rovigo": "RO",
  "treviso": "TV",
  "belluno": "BL",
  "vicenza": "VI",
  "gorizia": "GO",
  "pordenone": "PN",
  "aosta": "AO",
  "ancona": "AN",
  "pesaro": "PU",
  "urbino": "PU",
  "macerata": "MC",
  "fermo": "FM",
  "ascoli piceno": "AP",
  "perugia": "PG",
  "terni": "TR",
  "viterbo": "VT",
  "rieti": "RI",
  "latina": "LT",
  "frosinone": "FR",
  "l'aquila": "AQ",
  "laquila": "AQ",
  "teramo": "TE",
  "pescara": "PE",
  "chieti": "CH",
  "campobasso": "CB",
  "isernia": "IS",
  "caserta": "CE",
  "benevento": "BN",
  "avellino": "AV",
  "salerno": "SA",
  "foggia": "FG",
  "barletta": "BT",
  "andria": "BT",
  "trani": "BT",
  "taranto": "TA",
  "brindisi": "BR",
  "lecce": "LE",
  "potenza": "PZ",
  "matera": "MT",
  "cosenza": "CS",
  "catanzaro": "CZ",
  "reggio calabria": "RC",
  "crotone": "KR",
  "vibo valentia": "VV",
  "messina": "ME",
  "trapani": "TP",
  "agrigento": "AG",
  "caltanissetta": "CL",
  "enna": "EN",
  "ragusa": "RG",
  "siracusa": "SR",
  "sassari": "SS",
  "nuoro": "NU",
  "oristano": "OR",
  "olbia": "SS"
};

/**
 * Returns the 2-letter uppercase province code for a given comune/city name.
 * Normalizes accents, spaces, and casing. Returns null if not found.
 */
export function getProvinceFromComune(comuneName?: string): string | null {
  if (!comuneName) return null;
  const clean = comuneName
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // remove accents
    .replace(/^comune\s+di\s+/i, "") // strip "comune di "
    .trim();

  if (!clean) return null;

  // Direct match
  if (COMUNI_PROVINCE_MAP[clean]) {
    return COMUNI_PROVINCE_MAP[clean];
  }

  // Partial or fuzzy match (e.g. "Massa e Carrara", "Forte Dei Marmi")
  for (const [key, prov] of Object.entries(COMUNI_PROVINCE_MAP)) {
    if (clean === key || clean.startsWith(key) || key.startsWith(clean)) {
      return prov;
    }
  }

  return null;
}
